server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1200

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: autoset
    driver-class-name: org.mariadb.jdbc.Driver
  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type : trace